SELECT
    CONCAT(WORKITEM_ID) AS c_key,
    CURRENT_TIMESTAMP() AS c_fetchdate,
    OBJECT_TYPE,
    OBJECT_KEY,
    SENT_APPR,
    ACTUAL_APPR,
    USER_ACTION,
    COMPLETE_DATE,
    COMPLETE_TIME
FROM "/ORS/APPR_LOG"
WHERE COMPLETE_DATE >= :left_complete_date
-- WHERE :left_complete_date <= CONCAT(SUBSTRING(COMPLETE_DATE, 0, 4), '-', SUBSTRING(COMPLETE_DATE, 5, 2), '-', SUBSTRING(COMPLETE_DATE, 7, 2))
-- 1621296000000 : Timestamp formats