SELECT
    CONCAT(REGID, LOG_ENTRY) AS c_key,
    CURRENT_TIMESTAMP() AS c_fetchdate,
    REGID,
    LOG_ENTRY,
    TIMESTAMP,
    STATUS,
    INT_AGENT
FROM "/OTX/PF01_T_1LOG"
WHERE :left_timestamp_date <= CONCAT(SUBSTRING(TIMESTAMP, 0, 4), '-', SUBSTRING(TIMESTAMP, 5, 2), '-', SUBSTRING(TIMESTAMP, 7, 2))